# Generated by Django 5.1.7 on 2025-04-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calification',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='calificacion'),
        ),
    ]
