# Generated by Django 5.1.7 on 2025-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_calification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calification',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='calificacion'),
        ),
    ]
